version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    image: rabbitmq:4-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "quests"
      RABBITMQ_DEFAULT_PASS: "quests"
    volumes:
      - rabbitmq-data:/var/lid/rabbitmq

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'

  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build:
      context: ./worker
    container_name: worker
    restart: always
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - RABBITMQ_HOST = rabbitmq
      - DATABASE_URL = postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
    ports:
      - '7000:7000'
      -
volumes:
  rabbitmq-data:
  postgres_data:
